# Generated by Django 5.2.1 on 2025-05-24 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = []
