# Generated by Django 5.2.1 on 2025-05-24 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_recipecache_options_favoriterecipe'),
        ('core', '0002_initial'),
    ]

    operations = [
    ]
